package common

const (
	COMMENT_STATUS_NORMAL   = "NORMAL"
	COMMENT_STATUS_DELETE   = "DELETE"
	COMMENT_STATUS_OUTRIGHT = "OUTRIGHT"
)

const (
	ORDER_STATUS_UNPAY   = "UNPAY"
	ORDER_STATUS_PAID    = "PAID"
	ORDER_STATUS_CONFIRM = "CONFIRM"
)

const (
	COMMENT_STATUS_UNCOMMENT = "UNCOMMENT"
)

const (
	INCOME_STATUS_EXTRACT = "EXTRACT"
)

const (
	EVENT_STATUS_SUCCESS = "SUCCESS"
	EVENT_STATUS_FAIL    = "FAIL"
)
